services:
  opensearch-l4x4-fm:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-l4x4-fm
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g
    ports:
      - "9203:9200"
    volumes:
      - geo_poc_os_l_4x4_fm:/usr/share/opensearch/data
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "8g"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'green\\|yellow'"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  geo_poc_os_l_4x4_fm:
